[project]
name = "pulumi-scratchpad"
version = "0.1.0"
description = "My pulumi+AWS project"
readme = "README.md"
requires-python = ">=3.13"
#where = "src"
dependencies = [
	"pulumi",
	"pulumi-aws",
	"arrow",
	"pulumi-kubernetes>=4.22.2",
	"pulumi-eks>=3.8.1",
	"requests>=2.32.3",
	"s3transfer>=0.12.0",
	"boto3>=1.38.4",
]

[tool.uv]
package = true
